### ISSUE TITLE
Add option to ignore pre-releases

### ISSUE THREAD

**Issue by jansepke** [sibbell/support#17]
would it be possible to add an option to ignore all releases that are marked as pre-releases?
So they won't trigger an email notification or appear in the recent releases list.

**Comment by davegaeddert** [comment]
Thanks for the suggestion @Jandalf, I'd thought about the same thing myself, but wasn't sure if anyone else would care for that level of control. I'll see what I can do about this.

**Comment by davegaeddert** [comment]
The newly rebuilt Sibbell ignores pre-releases by default, they can be enabled as a part of the Sibbell "Pro" plan: https://sibbell.com/pricing
