### ISSUE TITLE
Change Email where the notifications are sent to

### ISSUE THREAD

**Issue by dkerzig** [sibbell/support#26]
I didn't find a way to change my mail address on which I want Sibbell-notifications are sent to.

**Comment by dkerzig** [comment]
push

**Comment by GlassGruber** [comment]
This.
Also going in https://sibbell.com/settings/ once you are logged in results in a 500 server error. Any guess?

**Comment by davegaeddert** [comment]
Haven't announced this yet formally, but in the new sibbell we now have the concept of "release monitors". You can choose the email address, Slack channel, or an RSS feed! 
http://help.sibbell.com/release-monitors/what-is-a-release-monitor
