### ISSUE TITLE
Show all new, concurrent releases for a repo

### ISSUE THREAD

**Issue by davegaeddert** [sibbell/support#27]
For a project like django/django, they released 3 new versions at once. Sibbell only shows what it thinks is the latest.
## ![image](https://cloud.githubusercontent.com/assets/649496/8599880/75bb87ee-2628-11e5-8fa4-76eba6c2733a.png)

![image](https://cloud.githubusercontent.com/assets/649496/8599867/6aac1846-2628-11e5-8daf-435a08dc1402.png)

**Comment by mathielen** [comment]
+1

**Comment by davegaeddert** [comment]
The new Sibbell handles this.
