### ISSUE TITLE
Email more responsive or email client friendly

### ISSUE THREAD

**Issue by j0k3r** [sibbell/support#28]
On some email client, the Sibbel email is really ugly. Every thing is fucked up and it's really hard to understand what goes to what.

Here is on Airmail on Mac:
![image](https://cloud.githubusercontent.com/assets/62333/8939971/b8f6e122-3567-11e5-8630-b0c647fd1f6b.png)

Here is on SparkMail on iPhone:
![image](https://cloud.githubusercontent.com/assets/62333/8940043/19bdcd86-3568-11e5-9d26-9af5cfb1cc0e.png)

I should suggest using a less complex html for this kind of email :)

**Comment by davegaeddert** [comment]
Thanks @j0k3r, the weekly email has been due for an overhaul for a while (you're right, there's a lot more going on than needs to be). I'll try and get on this sooner rather than later.

**Comment by j0k3r** [comment]
Any news about that point?

**Comment by bastelfreak** [comment]
@davegaeddert would it also be possible to send a non html part via mail? Let me know if you want to have a separate issue/feature request for this.

**Comment by davegaeddert** [comment]
Sorry, no updates on this yet.

@bastelfreak I haven't looked at this recently, but I would have thought that it already sends a plain text version with it. I'm using Google Inbox now though and can't find a way to verify that. Go ahead and make a separate issue for this, thanks!

**Comment by davegaeddert** [comment]
The new emails should be much better about this (check out the newly rebuilt sibbell.com if you haven't already):
![image](https://cloud.githubusercontent.com/assets/649496/20844496/ae9e91b4-b885-11e6-9237-b6262b5675de.png)
