### ISSUE TITLE
Ignored repos which were starred after account creation

### ISSUE THREAD

**Issue by cortopy** [sibbell/support#32]
I've created my sibbell account and I'm getting email notifications for new releases. However, I've noticed that only repositories which I starred BEFORE I created the account are taken into account. Those that I have starred since are ignored. I don't get emails for the newly starred repos and they don't appear in my [recent packages](https://sibbell.com/github/recent/) page either.

I've tried deleting my account and creating it again, but data doesn't seem to be deleted from server either. When creating account I only see new releases for the old repositories

**Comment by Osspial** [comment]
I'm getting the same issue. Is there any way to refresh Sibbell's repository list?

**Comment by davegaeddert** [comment]
This should hopefully be address in the newly rebuilt Sibbell. We check GitHub for updates to starred/watched repos every ~3 hrs.
