### ISSUE TITLE
Clarify Add-On Pricing

### ISSUE THREAD

**Issue by kevindb** [sibbell/support#37]
Please add some clarifying text or an FAQ explaining that each of the four Add-Ons is a separate $2 per month payment. In other words, a fully upgraded account would cost $8 /mo, not $2 /mo. I was only able to find this information on your person blog at http://davegaeddert.com/2015/05/19/sibbell-a-saas-pricing-experiment/.

That said, awesome app! Thank you!

**Comment by davegaeddert** [comment]
Thanks @kevindb! I've actually been planning on simplifying the pricing model to where it's just one price to use all the "pro" features. What's your take on that? If it were around $5 / mo. to use everything, would you go for that? Can't help but notice you didn't pull the trigger on any of the $2 features...

**Comment by kevindb** [comment]
I actually found the separate addon somewhat refreshing. It was just so unusual that I didn't understand what was going on at first. I'm really only interested in Choose Repos and Weekly Digest, so those two for $4 is better for _me_ than all four for $5.
I just signed up today. I was planning to see how the notifications went before diving into paid upgrades.

**Comment by davegaeddert** [comment]
The "add-on" system is gone. The newly launched Sibbell just has a "Pro" plan, with all the previous features combined and more to come.

**Comment by davegaeddert** [comment]
https://sibbell.com/pricing/
