### ISSUE TITLE
Server error 500 on connecting with GitHub

### ISSUE THREAD

**Issue by geocodingtakeaway** [sibbell/support#44]
Connecting with GitHub on the homepage yields a server error:

[https://sibbell.com/login/github/?next=/about/](https://sibbell.com/login/github/?next=/about/)

**Comment by maital** [comment]
I'm having the same issue for a few days now

**Comment by davegaeddert** [comment]
@maital @geocodingtakeaway sorry for the trouble here -- Sibbell is under some serious load these days. Go ahead and give it another try and let me know if you still have trouble.

**Comment by pinny87** [comment]
I am also getting the same error.

**Comment by tavrez** [comment]
I am trying to login from a week ago and I get this error everytime I try

**Comment by ybozhko** [comment]
Looks like the problem still exists. I really wanted to give it a try, but cannot login with the same "Server Error (500)" :(

**Comment by davegaeddert** [comment]
@pinny87 @tavrez @ybozhko I tried to clean up your accounts -- feel free to give it another try

**Comment by ybozhko** [comment]
Seems to be working now. Thanks! :)

**Comment by tavrez** [comment]
Working for me, thanks.

**Comment by pinny87** [comment]
Working.

Thanks.

**Comment by Mihara** [comment]
Well, I am still getting error 500...

**Comment by notDavid** [comment]
Github login -> Server Error (500)

**Comment by wiebl** [comment]
Error 500 for me as well

**Comment by guidob** [comment]
Same here, anything that can be done to have this fixed?

**Comment by thuandt** [comment]
Same here :(

**Comment by jcruzs** [comment]
Unfortunately I'm having the same error. Thanks in advance for any help.

**Comment by jean-christophe-manciot** [comment]
Same here.

**Comment by labithiotis** [comment]
Same here, also got an email to confirm email address that throws same error

**Comment by davegaeddert** [comment]
Hey everybody -- sorry for the issues here. The truth is simply that Sibbell is in need of some attention that I just don't have the time to give it right now. Sibbell functions on polling so that nobody has to add webhooks to repos for it to work, but unfortunately that's become pretty demanding -- as of right now it is aware of 214,709 repos! It needs some optimization work, and it needs to make some money to pay the hosting costs (both of which are going to take some energy to do effectively) ;)

I'll try and keep it up and running as best I can in the meantime. Just comment here if your login fails...

@Mihara @notDavid @wiebl @guidob @thuandt @jcruzs @aprilhalasz @jean-christophe-manciot @labithiotis  -- feel free to try logging in again

**Comment by labithiotis** [comment]
Great, works perfectly for me now. Thank you :)

**Comment by jean-christophe-manciot** [comment]
I received some e-mail notifications the past days, but now:
- sibbel.com gives me "Server Error (500)"
- previously, settings gave me "502 Bad Gateway"

**Comment by jean-christophe-manciot** [comment]
When I can access it:
- sibbell.com/github/recent/ is blank ("No releases so far this week")
- /sibbell.com/github/weekly/ is also blank

**Comment by jean-christophe-manciot** [comment]
Thanks for solving that.

**Comment by Miradorn** [comment]
Also 500 error, can you fix ist please? Thanks!

**Comment by zx8** [comment]
Me too!

**Comment by geldmacher** [comment]
I'm not able to go to settings as well. I get a 500 error ...

**Comment by PrickyRex** [comment]
I get Server Error (500) as well. Been trying to connect for weeks, would really appreciate this program working!

**Comment by Zodiase** [comment]
Keep getting either 502 or 504 here.

**Comment by dnepro** [comment]
+1 also receiving error 500

**Comment by remijean** [comment]
Also 500 error, help plz !

**Comment by matt-snider** [comment]
Same here :cry:

**Comment by lucdg** [comment]
same here

**Comment by neok-m4700** [comment]
Same for me !

**Comment by infantito** [comment]
I'm crying! :'(

**Comment by davegaeddert** [comment]
Hey everybody, sorry for the issues. Same story as above I'm afraid -> https://github.com/sibbell/sibbell-issues/issues/44#issuecomment-208526678

Thanks for your patience! Give it another try and leave a comment if you still have issues.

cc @infantito @neok-m4700 @lucdg @matt-snider @remijean @dnepro @Zodiase @PrickyRex @geldmacher @zx8 @Miradorn

**Comment by mvanroon** [comment]
Maybe consider introducing some tiers? Free-premium-corporate kinda thing? To pay for the hosting costs?

**Comment by davegaeddert** [comment]
Thanks @mvanroon, I tried to add some paid features a while back but I'd consider it a failed "experiment". It is incredibly encouraging to see how badly people still want to use Sibbell, despite the instability it's had for a little while now. I will definitely do some thinking on the best next steps for giving this the attention it deserves!

**Comment by mvanroon** [comment]
maybe a Paypal donate button instead?

**Comment by davegaeddert** [comment]
@mvanroon yeah, potentially. Although I've never really heard of anyone having success with that. I'd much rather figure out a better paid tier that people are willing to pay for ;)

**Comment by mvanroon** [comment]
bare in mind that installing a paypal donate button on your github page takes 5 minutes and setting up subscriptions takes a lot longer

**Comment by iForests** [comment]
Getting 500 error, please help.

**Comment by davegaeddert** [comment]
The newly rebuilt SIbbell is up and running, this should no longer be an issue! A lot of people have expressed interest in helping in various ways. I appreciate it, and I can tell you hands down that the most helpful way to support us now is to subscribe to our "Pro" plan -- the cost is as pretty low and we're going to deliver all the features around how you receive notifications through there. Thanks for all your support!

https://sibbell.com/pricing/
