### ISSUE TITLE
[Enhancement] Allow notifications from other Git repositories

### ISSUE THREAD

**Issue by jean-christophe-manciot** [sibbell/support#47]
For example from:
- https://git.ganeti.org
- https://git.gnupg.org
- https://git.xiph.org
- https://gitlab.com
- https://git.annexia.org/git
- https://libvirt.org/
- https://git.kernel.org/
- https://git.code.sf.net
- https://git.savannah.nongnu.org
- https://anongit.freedesktop.org/
- https://git.fedorahosted.org/
- ...

**Comment by pydolan** [comment]
Similarly, Bitbucket support would be great.

**Comment by davegaeddert** [comment]
Quick update here -- we don't have any plans to add this to Sibbell right now. We did recently launch https://www.dependencies.io though which can do this (along with actually updating your dependencies). Let me know if you have any questions about it.
