### ISSUE TITLE
Not being able to sign in

### ISSUE THREAD

**Issue by je-vv** [sibbell/support#50]
Getting the error:

Server Error (500)

When accessing:

https://sibbell.com

And attempting to login with github...  The final web page failing:

https://sibbell.com/complete/github/?code=b345e93c2d1e19841c63&redirect_state=rITqWLnxbiA81fy6g6zhF4zA4qR72JIa&state=rITqWLnxbiA81fy6g6zhF4zA4qR72JIa

**Comment by wunc** [comment]
+1

**Comment by mitchelllisle** [comment]
+ 1

**Comment by chteuchteu** [comment]
+1

**Comment by davegaeddert** [comment]
The new, rebuilt Sibbell is up. Shouldn't be an issue anymore.
