### ISSUE TITLE
For "last release date", the year would be beneficial

### ISSUE THREAD

**Issue by BobDankert** [sibbell/support#51]
I watch some repos which haven't been updated in a while. It would be helpful if the year was shown for the last release/publish date.

**Comment by davegaeddert** [comment]
Not sure exactly which part of the UI this was referring to originally, but the newly rebuilt Sibbell hopefully addresses this in most places!
![image](https://cloud.githubusercontent.com/assets/649496/20844190/52108714-b884-11e6-94db-f6ac6ea9b304.png)
