### ISSUE TITLE
[Enhancement] Monitor Docker Hub's starred projects for changes

### ISSUE THREAD

**Issue by pydolan** [sibbell/support#56]
This may be outside the scope of Sibbell's goals, but I think it would be useful to add this. Thanks

**Comment by davegaeddert** [comment]
Quick update on this -- we don't have any plans to do this right now. We did recently launch https://www.dependencies.io though which does have support for Docker. It can even update your Dockerfiles in your repo for you ;) Let me know if you have any questions about it.
