### ISSUE TITLE
Watching your own repo (private repo)

### ISSUE THREAD

**Issue by okohll** [sibbell/support#58]
Hi, great product.

Strange as it may seem, I'd like to receive notifications about a private repository that I'm the owner of. When I look in Manage Repos, I only see public repos that I've starred. Is it possible to monitor my own private one?

The reason is that I'd like to give notifications of new releases to a third party (email or RSS), even though they don't have rights to log in to Github and see the source code.

Is anything like that possible?

Cheers
Oliver

**Comment by davegaeddert** [comment]
Hi @okohll,

Sibbell currently doesn't ask for private repo access, so it won't be able to use private repos. We're planning a major overhaul of Sibbell though, both in terms of performance and features and definitely are planning on this!

**Comment by OSTraining** [comment]
+1 on this request

**Comment by davegaeddert** [comment]
@OSTraining can you say a little more about how/why you would use this? Just to give us a better idea of what exactly people are trying to accomplish.

**Comment by OSTraining** [comment]
We have some private repos for thing such as WordPress plugins.

We'd like easy access to the changelogs, perhaps in an RSS feed.

**Comment by davegaeddert** [comment]
@OSTraining ok thanks. So assuming this would be a Sibbell Pro feature, is this something you'd pay $6 / month for?

**Comment by OSTraining** [comment]
Yes, it would

**Comment by davegaeddert** [comment]
Cool, thanks.

If anybody else is interested in using private repos on Sibbell, please leave a comment here with a little explanation of how you/why you would use it.

**Comment by davegaeddert** [comment]
Quick update on this -- we have no plans to integrate with private repos right now with Sibbell. We started working on a real GitHub integration, but it just pushed us to build https://www.dependencies.io instead. This (and a lot of other things) could be done using that, let us know if you have any questions about it.
