### ISSUE TITLE
ANNOUNCEMENT: Major updates to Sibbell are coming

### ISSUE THREAD

**Issue by davegaeddert** [sibbell/support#60]
Just want to put this out there so people know -- we're currently in the process of rebuilding Sibbell. We know it hasn't received the attention that it deserves over the last number of months, and stability has been an issue with the scale that it's currently operating at. Everyone's comments and support mean a lot and has re-inspired us to take a look at Sibbell with fresh eyes, as it feels as though there is certainly something here worth pursuing.

So we're currently in the process of revamping Sibbell. We're starting by simplifying and improving the functionality that Sibbell currently handles today, which we don't expect to take long. You will still be able to use it for free just like you can today, and we're going to combine the paid features into a single subscription plan that we hope will be more appealing to our users.

After we've got things back up and running how they should be, we do have plans for next steps that we're very excited about. 

We'll make an announcement to all existing users when we're ready to re-launch, but feel free to subscribe to notifications on this issue as we'll post any updates here as well.

Thanks for all of your support!

**Comment by nadeemja** [comment]
Hi! 

Really like the sound of this! 

Could you update us on the progress since the announcement? 

For the last weeks, Sibbell has been working sporadically.

**Comment by davegaeddert** [comment]
Hi @nadeemja, glad to hear it!

I can certainly give an update, thanks for asking. We've actually had the new sibbell running in the background for about a week -- things have been running well and we're in the process of migrating all of our existing users over as seamlessly as possible. Our goal is to require essentially no work on your end (the user). We're planning to switch things over this coming week if all goes well, we're just monitoring and tweaking things to make sure it's all scaling properly as we import users.

**Comment by nadeemja** [comment]
That's  awesome, @davegaeddert! Can't wait :)

**Comment by davegaeddert** [comment]
As some may have noticed, the new Sibbell was put up at the end of last week. Things seem to be running well -- I'd encourage you to go to sibbell.com and check it out if you haven't! We'll probably send an email out to all existing users with more information about where things are headed, but feel free to add any questions/feedback here if you have them.
