### ISSUE TITLE
"Recent releases" not up to date

### ISSUE THREAD

**Issue by arnemertz** [sibbell/support#61]
Hi, first of all, thanks for this great tool!

Today I came across what seems a glitch in the recent releases: 
I have starred and received notifications for https://github.com/nlohmann/json. However, Sibbell shows the most recent release of that repo to be 2.0.5, but, actually, there are two newer releases, 2.0.6 and 2.0.7:
https://github.com/nlohmann/json/releases
Something similar happens for https://github.com/conan-io/conan: Latest release is 0.14.1, Sibbell shows 0.13.2 (3 releases behind)
For https://github.com/rollbear/trompeloeil I get shown no release at all, while there have been releases more recently than the shown release 2.0.5 of nlohmann/json

**Comment by davegaeddert** [comment]
@arnemertz thanks for letting us know. We're aware Sibbell hasn't been able to keep up lately. Check out #60 -- we're planning to roll out a completely new Sibbell very soon!
