### ISSUE TITLE
Sibbell is making thousands of Github API requests with my account

### ISSUE THREAD

**Issue by danielbachhuber** [sibbell/support#62]
I wrote into Github support about an API rate limit block on my account:

> I'm getting the following message when using hub:
> > API rate limit exceeded for danielbachhuber.
> 
> I haven't been using Github all day though, so I'm not sure why I'm hitting the rate limit. Can you share more insight into what might be making requests on my behalf?

This is what they replied with:

> After checking your account's API usage, our logs indicate there is room for optimization. Below is a high-level summary of your account's usage for November 28, 2016 from 12PM to 1PM. I scoped it for this date and time because this was the most recent instance of your account surpassing the API rate limit.
> 
> This is a breakdown of your requests by user_agent:
> 
> ```
> Composer/source (Linux; 2.6.32-642.6.2.el6.x86_64; PHP 5.5.38)  2,569   50.195% 
> sibbell 2,500   48.847% 
> Octokit Ruby Gem 4.6.1  35  0.684%  
> Hub 2.2.9   7   0.137%  
> Travis-CI-Gatekeeper/Faraday    5   0.098%  
> GH/0.14.0   2   0.039%  
> ```
> 
> More than half your requests are being made from Composer/source. The other user_agent making the most requests is sibbell.
>
> **sibbell's requests**
> 
> Here are sibbell's requests, broken down by the top routes:
>
>```
> /repositories/:repository_id/git/commits/:id    1,230   49.2%   
> /repositories/:repository_id/releases   437 17.48%  
> /repositories/:repository_id/git/tags/:id   424 16.96%  
> /repositories/:repository_id/git/refs/* 409 16.36%  
> ```
>
> All 2,500 of those requests were GET requests. Here's a general breakdown of their statuses:
> 
> ```
> 200 2,118   84.72%  
> 404 250 10% 
> 304 129 5.16%   
> 409 3   0.12%
> ```
>
> Most of them returned a successful status, but there were a few that resulted in either a 404 or 409. Those 304s are the result of conditional requests.

**Comment by davegaeddert** [comment]
Thanks for passing this along @danielbachhuber. Looks like Composer combined with Sibbell blew past the 5000 / hr / OAuth rate limit (https://developer.github.com/v3/#rate-limiting). I wasn't aware that they combined like that to restrict your account entirely, I always assumed that a particular service would hit it's own rate limit, which it could then deal with.

We're transitioning over to a newly built Sibbell and syncing releases from GitHub -- some of the repos you have starred must have a ton of releases as commit tags. We've put some serious caching and conditional logic in place so hopefully after this initial run through, we'll be getting a lot of 304s which shouldn't count towards any rate limits.

Sorry if it caused you any trouble. We'll give some thought towards what else we can do to avoid issues like this.

**Comment by danielbachhuber** [comment]
> We're transitioning over to a newly built Sibbell and syncing releases from GitHub -- some of the repos you have starred must have a ton of releases as commit tags. We've put some serious caching and conditional logic in place so hopefully after this initial run through, we'll be getting a lot of 304s which shouldn't count towards any rate limits.

Ah, that would explain it :)

> Sorry if it caused you any trouble. We'll give some thought towards what else we can do to avoid issues like this.

No worries! Just wanted to share for general reference.
