### ISSUE TITLE
Release are shown twice

### ISSUE THREAD

**Issue by unixfox** [sibbell/support#63]
Some releases are shown twice, here is a proof:
![sibbel](https://cloud.githubusercontent.com/assets/4016501/20827306/6d5f1de0-b871-11e6-85cd-b228a6095be4.PNG)

**Comment by davegaeddert** [comment]
Sure enough. We've seen that a couple places where they delete and then re-tag a different commit. We'll take a look.

**Comment by davegaeddert** [comment]
Ok, this should be resolved now. Thanks @unixfox for making an issue!
