### ISSUE TITLE
Email notifications are often delayed a few days

### ISSUE THREAD

**Issue by bwood** [sibbell/support#68]
On 12/8 [this release|https://github.com/pantheon-systems/drops-7/releases/tag/7.53] was created.

I didn't get the email notification about this release until 12/11.

Here is the full headers for the sibbell notification: 
<img width="912" alt="screen shot 2016-12-12 at dec 12 201601 35 pm" src="https://cloud.githubusercontent.com/assets/185537/21120436/38b8d064-c07c-11e6-9a83-d7211fe4c604.png">

**Comment by davegaeddert** [comment]
@bwood I can't find any reason for the delay on our end. I can see that that repo has been checked multiple times every day between those dates, and that release didn't seem to exist until we checked on 12/12 12:47am CST. Like I mentioned before, I wonder if maybe they didn't push it to GitHub until then?

I'm going to close this for now. If you learn anything new there or have other examples, please pass them along! We'll keep an eye out for similar issues.
