### ISSUE TITLE
Add a way to ignore nightly releases

### ISSUE THREAD

**Issue by steelbrain** [sibbell/support#82]
I have unstarred several projects in the past mainly because then sibbel would spam me with their nightly release emails. IMHO there should be a way to ignore releases with a certain name or something. What do you think?

**Comment by davegaeddert** [comment]
Definitely agree. Can you point to a couple of the repos so we take a look and see how they use releases?

In general we're hoping to add some more options to Sibbell Pro for how you can create a monitor. So maybe some special `prereleases=false` type flags and if they don't use that, then yeah maybe some kind of basic regular expression or something you can filter with on the release/tag name.

**Comment by steelbrain** [comment]
There's [servo](https://github.com/servo/servo/releases) that deletes the old release with same name and publishes a new one every day or two.

Then there's [Micro](https://github.com/zyedidia/micro/releases) that does the same thing I think (deleting old release and tagging new with same name).

Then there's [youtube-dl](https://github.com/rg3/youtube-dl/releases) that publishes a new release with that every now and then. While they are not exactly nightly, I would still like a way to ignore it entirely without un-starring it

**Comment by davegaeddert** [comment]
Quick update here -- we don't have any plans to add this to Sibbell right now. A lot of these kinds of problems are what pushed us to build https://www.dependencies.io (which can update your actual repo dependencies).
