### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jogc** [sibbell/support#90]
I repeatedly get 502 Bad Gateway when I try to access https://sibbell.com/github/releases/

**Comment by davegaeddert** [comment]
Are you still having trouble with this? I noticed the same while we were pushing a couple updates, but it only lasted for a minute or two. I'll close it for now but let me know if there's still a problem.

**Comment by jogc** [comment]
Yeah I still get 502 Bad Gateway/nginx/1.10.2.
I have a Singapore IP address if that matters


2018-02-19 3:33 GMT+08:00 Dave Gaeddert <notifications@github.com>:
