### ISSUE TITLE
Too many "new release" emails - could we get a "daily digest" option?

### ISSUE THREAD

**Issue by axefrog** [sibbell/support#91]
I've got hundreds of repositories starred on Github. I like receiving notifications about the ones that have new releases, but I get these notifications constantly throughout the day. It fills my inbox with noise, and probably adds a lot to your transactional email bill. Have you considered adding a "daily digest" option in notification preferences? You could then send one email with a list of new releases that day, rather than 75 separate emails throughout the day.

![image](https://user-images.githubusercontent.com/298883/36819087-98ea397c-1d33-11e8-8816-cac874ef0572.png)

**Comment by davegaeddert** [comment]
Take a look at [Sibbell Pro](https://about.sibbell.com/personal/pricing/) -- it gives all kinds of flexibility through "release monitors", including daily and weekly digests. 

https://sibbell.com/settings/
http://help.sibbell.com/release-monitors/what-is-a-release-monitor

**Comment by axefrog** [comment]
For what it's worth, it means I'll now unsubscribe, and probably forget about Sibbell after a while. If I was receiving a daily digest of open source releases, you'd still be able to remind me that your product exists, and then when I discover that it fulfills a need I'm willing to pay for, it'd be in the front of my mind and you'd get my business. Instead, I will have long forgotten about it because I had to unsubscribe because I was receiving too many emails.

**Comment by davegaeddert** [comment]
Fair enough. I'll keep it in mind for the future. We've tried a number of things over the years in terms of a revenue model and never seem to have gotten it quite right. It will probably get some attention again later this year, but it's not a priority right now.

Thanks for the feedback!
