### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by fedebaier** [sibbell/support#92]
I registered a few minutes ago, and every time I try to enter to https://sibbell.com/github/releases/ I get a 502 error.

Also, I starred a couple more projects in GitHub and I don't see them in https://sibbell.com/github/projects/

**Comment by davegaeddert** [comment]
Hey @fedebaier, I haven't found any issues yet. Are you still having this problem consistently? What country are you in?

On the starred projects -- Sibbell syncs those every ~8 hrs or so, so they won't show up immediately.

**Comment by fedebaier** [comment]
I checked now and it worked well, so I don’t know what could have happened. I’m closing the issue. Thanks for the reply, though 👍

**Comment by luusl** [comment]
The error seems to be back again.
