### ISSUE TITLE
Syncing Github starred repos

### ISSUE THREAD

**Issue by tahaburak** [sibbell/support#93]
Hello, 

I've just started using sibbell and it seems really good. However, I've realized that I have lots of starred repos and decided to clean them. Now that I cleaned those I couldn't find a way to sync them on sibbell so that it doesn't follow those. 

I have tried to revoke sibbell's access to my account but this didn't change my account info on sibbell. 
Is it possible that you delete my account and I can have a fresh start on sibbell ? 

Thanks in advance.

**Comment by davegaeddert** [comment]
Hi @tahaburak, Sibbell doesn't sync immediately with GitHub when you star/unstar repos (there aren't any webhooks to tell us you did that). Instead, we go out and check for changes every ~8 hrs or so. Have the changes you were looking for come through by now? I can delete your account if you want... just let me know.

**Comment by tahaburak** [comment]
Ah, just checked and my repos synced yes! No need to delete my account and feel free to close the issue. Thanks :)

**Comment by davegaeddert** [comment]
Sounds good!
